### ISSUE TITLE
Kali Linux conflicting dependencies

### ISSUE THREAD

**Issue by mattbrun** [s0lst1c3/eaphammer#1]
Hello,
First of all thanks for your effort in this project!

Installing the required dependencies on Kali Linux rolling release - just installed and upgraded - I found the `libssl-dev` and `libssl1.0-dev` conflict.
Which one is the correct one?

Cheers

PS: I tried to install both of them, but I still have troubles on the `hostapd` part. For that i'll open another issue.

**Comment by s0lst1c3** [comment]
The libssl1.0-dev is actually for a component of hostapd-wpe that isn't used for this project. Hostapd-wpe has module that can be used to test for the Heartbleed vulnerability. Doing this requires an older version of OpenSSL, hence the libssl1.0-dev dependency. Unfortunately, I think this may be causing compatibility issues with newer supplicants, which I think is the problem you were facing in #3. I'll explain further in the notes section for that issue.
