### ISSUE TITLE
 Failed to load client certificate error:140AB18E:SSL /  certificate:ca md too weak

### ISSUE THREAD

**Issue by AcidMand04** [s0lst1c3/eaphammer#12]
Hi Getting this error when running it. 
Certificate was generated ok but ... :

OpenSSL: tls_global_client_cert - Failed to load client certificate error:140AB18E:SSL routines:SSL_CTX_use_certificate:ca md too weak
OpenSSL: pending error: error:140AB18E:SSL routines:SSL_CTX_use_certificate:ca md too weak
TLS: Failed to set global parameters
Failed to set TLS parameters
Interface initialization failed
wlan0: interface state UNINITIALIZED->DISABLED
wlan0: AP-DISABLED 
wlan0: Unable to setup interface.
wlan0: interface state DISABLED->DISABLED
wlan0: AP-DISABLED 
hostapd_free_hapd_data: Interface wlan0 wasn't started
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
press enter to quit...

**Comment by s0lst1c3** [comment]
Resolved by e47aca483de9724918cf913370611e07b2f9d1db
