### ISSUE TITLE
Dependancy update - Responder 

### ISSUE THREAD

**Issue by yellow-starburst** [s0lst1c3/eaphammer#121]
Tool relies on 2.3.3.9 of responder. Responder went through massive changes in the update and eaphammer will no longer work with the changes.

**Comment by s0lst1c3** [comment]
Thanks for the heads up. I’ll likely end up grabbing an earlier release as a quick temporary fix, then do another update to get it to work with the real one.

**Comment by s1nglethr3ad** [comment]
For me Responder appeared to not be starting.  Looked like an error with RDP settings.  I edited the Responder.ini file in folder /eaphammer/settings/core.  Added line:

RDP = On

No more error starting eaphammer.

This is the error I was getting:
Traceback (most recent call last):
   File "/root/eaphammer/local/Responder/Responder.py", line 58 in <module>
      settings.Config.populate(options)
   File "/root/eaphammer/local/Responder/settings.py", line 98, in populate
      self.RDP_On_Off           =self.toBool(config.get('Responder Core', 'RDP'))
   File "/usr/lib/python2.7/ConfigParser.py", line 618, in get
      raise NoOptionError(option, section)
ConfigParser.NoOptionError:  No option 'rdp' in section: 'Responder Core'

Hope this helps.
Cheers!

**Comment by betoatx** [comment]
Thanks. I cloned eaphammer today and got this error when running --hostile-portal. This fixed it!

**Comment by cyberlama** [comment]
Can confirm that the latest version that i pulled today still has this issue and the easy fix that should be incorporated is what @s1nglethr3ad suggested by adding in 

RDP = On 

into the eaphammer/settings/core/responder.ini file

This will also allow you to use the latest version of responder 3.0.1.0 also which i git pulled down into eaphammer/local/Responder directory for testing purposes.

**Comment by s0lst1c3** [comment]
Sounds like a great candidate for a pull request! :)
