### ISSUE TITLE
Upgraded/install newest setup, now receiving hostapd errors

### ISSUE THREAD

**Issue by b4cktr4ck2** [s0lst1c3/eaphammer#129]
**Describe the bug**
Cloned master branch today, re-ran kali-setup to install newest packages. Now whenever I try to run eaphammer I recieve the following errors:
Line 24: unknown configuration item 'loud_karma'
Line 25: unknown configuration item 'known_beacons'
Line 47: unknown configuration item 'capture_wpa_handshakes'
Line 48: unknown configuration item 'psk_capture_file'

**To Reproduce**

1. git clone master branch
2. run kali-setup script
3. Generate cert with eaphammer --cert-wizard
4. run example command "./eaphammer -i wlan0 --channel 4 --auth wpa-eap --essid CorpWifi --creds"

**Expected behavior**

Eaphammer to not error out, or install version of hostapd that supports these configuration options.

**Command string(s) used**

The exact command(s) you used to trigger the bug.

**EAPHammer verbose output (using the --debug flag)**

➜  eaphammer git:(master) ✗ sudo ./eaphammer -i wlan1 --channel 4 --auth wpa-eap --essid CorpWifi --creds --debug

                     .__                                         
  ____ _____  ______ |  |__ _____    _____   _____   ___________ 
_/ __ \\__  \ \____ \|  |  \\__  \  /     \ /     \_/ __ \_  __ \
\  ___/ / __ \|  |_> >   Y  \/ __ \|  Y Y  \  Y Y  \  ___/|  | \/
 \___  >____  /   __/|___|  (____  /__|_|  /__|_|  /\___  >__|   
     \/     \/|__|        \/     \/      \/      \/     \/       

                        Rogue AP attacks for operators.

                             Version:  1.12.0
                            Codename:  Power Overwhelming
                              Author:  @s0lst1c3
                             Contact:  gryan@specterops.io

    
[?] Am I root?
[*] Checking for rootness...
[*] I AM ROOOOOOOOOOOOT
[*] Root privs confirmed! 8D
[debug] Settings:
{
    "core": {
        "eap_user_methods": {
            "peap_version": {
                "gtc_downgrade": "1"
            },
            "phase1": {
                "balanced": "PEAP,TTLS,TLS,FAST",
                "gtc_downgrade": "PEAP",
                "speed": "PEAP,TTLS,TLS,FAST",
                "weakest": "PEAP,TTLS,TLS,FAST"
            },
            "phase2": {
                "balanced": "GTC,MSCHAPV2,TTLS-MSCHAPV2,TTLS,TTLS-CHAP,TTLS-PAP,TTLS-MSCHAP,MD5",
                "gtc_downgrade": "GTC",
                "speed": "MSCHAPV2,TTLS-MSCHAPV2,TTLS,TTLS-CHAP,GTC,TTLS-PAP,TTLS-MSCHAP,MD5",
                "weakest": "GTC,TTLS-PAP,MD5,TTLS-CHAP,TTLS-MSCHAP,MSCHAPV2,TTLS-MSCHAPV2,TTLS"
            }
        },
        "eaphammer": {
            "general": {
                "default_ssid_list": "example_known_ssids_file.txt",
                "default_wordlist": "rockyou.txt",
                "openssl_build_options": "'enable-ssl2 enable-ssl3 enable-ssl3-method enable-des enable-rc4 enable-weak-ssl-ciphers no-shared'",
                "openssl_source": "'https://github.com/openssl/openssl/archive/OpenSSL_1_1_1a.tar.gz'",
                "openssl_version": "'1.1.1a'",
                "proc_ipforward": "/proc/sys/net/ipv4/ip_forward",
                "version": "'0.1.4'",
                "wordlist_source": "https://github.com/danielmiessler/SecLists/blob/43e28e38957f456cac37d29e6596284cd7c88f90/Passwords/rockyou.txt.tar.gz?raw=true"
            },
            "services": {
                "dnsmasq": "dnsmasq",
                "dnsmasq_bin": "dnsmasq",
                "dnsmasq_sleep": "2",
                "dnsspoof": "None",
                "dnsspoof_bin": "dnsspoof",
                "dnsspoof_sleep": "2",
                "httpd": "apache2",
                "httpd_bin": "None",
                "httpd_sleep": "2",
                "network_manager": "network-manager",
                "network_manager_sleep": "2",
                "sleep_time": "2",
                "use_systemd": "True",
                "wlan_clean_sleep": "2",
                "wpa_supplicant": "wpa_supplicant",
                "wpa_supplicant_bin": "None",
                "wpa_supplicant_sleep": "2"
            }
        },
        "hostapd": {
            "80211n": {
                "ieee80211n": "1",
                "require_ht": "0"
            },
            "args": {
                "debug": "False"
            },
            "eap": {
                "capture_wpa_handshakes": "0",
                "eap_fast_a_id": "101112131415161718191a1b1c1d1e1f",
                "eap_fast_a_id_info": "hostapd-wpe",
                "eap_fast_prov": "3",
                "eap_server": "1",
                "ieee8021x": "1",
                "pac_key_lifetime": "604800",
                "pac_key_refresh_time": "86400",
                "pac_opaque_encr_key": "000102030405060708090a0b0c0d0e0f",
                "wpa_key_mgmt": "WPA-EAP"
            },
            "general": {
                "beacon_int": "100",
                "bssid": "00:11:22:33:44:00",
                "channel": "1",
                "country_code": "US",
                "ctrl_interface": "./run/hostapd-control-interface",
                "ctrl_interface_group": "0",
                "driver": "nl80211",
                "dtim_period": "1",
                "fragm_threshold": "2346",
                "hw_mode": "g",
                "ieee80211w": "0",
                "ignore_broadcast_ssid": "0",
                "interface": "wlan0",
                "known_beacons": "0",
                "logger_stdout": "-1",
                "logger_stdout_level": "2",
                "logger_syslog": "-1",
                "logger_syslog_level": "2",
                "loud_karma": "0",
                "macaddr_acl": "0",
                "max_num_sta": "255",
                "rts_threshold": "2347",
                "ssid": "eaphammer",
                "ssid_acl_mode": "0",
                "use_autocrack": "0",
                "use_karma": "0"
            },
            "owe": {
                "owe_ieee80211w": "2",
                "rsn_pairwise": "CCMP",
                "wpa": "2",
                "wpa_key_mgmt": "OWE"
            },
            "owe_transition": {
                "owe_transition_bssid": "fe:e1:de:ce:a5:ed",
                "owe_transition_ieee80211w": "2",
                "owe_transition_ignore_broadcast_ssid": "1",
                "owe_transition_ssid": "remmahpae",
                "rsn_pairwise": "CCMP",
                "wpa": "2",
                "wpa_key_mgmt": "OWE"
            },
            "psk": {
                "capture_wpa_handshakes": "1",
                "wpa_passphrase": "ermahgerdbestpasswordevar"
            },
            "wmm": {
                "wmm_ac_be_acm": "0",
                "wmm_ac_be_aifs": "3",
                "wmm_ac_be_cwmax": "10",
                "wmm_ac_be_cwmin": "4",
                "wmm_ac_be_txop_limit": "0",
                "wmm_ac_bk_acm": "0",
                "wmm_ac_bk_aifs": "7",
                "wmm_ac_bk_cwmax": "10",
                "wmm_ac_bk_cwmin": "4",
                "wmm_ac_bk_txop_limit": "0",
                "wmm_ac_vi_acm": "0",
                "wmm_ac_vi_aifs": "2",
                "wmm_ac_vi_cwmax": "4",
                "wmm_ac_vi_cwmin": "3",
                "wmm_ac_vi_txop_limit": "94",
                "wmm_ac_vo_acm": "0",
                "wmm_ac_vo_aifs": "2",
                "wmm_ac_vo_cwmax": "3",
                "wmm_ac_vo_cwmin": "2",
                "wmm_ac_vo_txop_limit": "47",
                "wmm_enabled": "1"
            },
            "wpa": {
                "auth_algs": "3",
                "wpa": "2",
                "wpa_pairwise": "TKIP CCMP"
            },
            "wrapper": {
                "sleep_time": "3"
            }
        },
        "responder": {
            "HTTP Server": {
                "exedownloadname": "ProxyClient.exe",
                "exefilename": "files/BindShell.exe",
                "htmlfilename": "files/AccessDenied.html",
                "htmltoinject": "<img src='file://RespProxySrv/pictures/logo.jpg' alt='Loading' height='1' width='1'>",
                "serve-always": "Off",
                "serve-exe": "Off",
                "serve-html": "Off",
                "wpadscript": "function FindProxyForURL(url, host){if ((host == \"localhost\") || shExpMatch(host, \"localhost.*\") ||(host == \"127.0.0.1\") || isPlainHostName(host)) return \"DIRECT\"; if (dnsDomainIs(host, \"ProxySrv\")||shExpMatch(host, \"(*.ProxySrv|ProxySrv)\")) return \"DIRECT\"; return 'PROXY ProxySrv:3128; PROXY ProxySrv:3141; DIRECT';}"
            },
            "HTTPS Server": {
                "sslcert": "certs/responder.crt",
                "sslkey": "certs/responder.key"
            },
            "Responder Core": {
                "analyzelog": "Analyzer-Session.log",
                "autoignoreaftersuccess": "Off",
                "capturemultiplecredentials": "On",
                "capturemultiplehashfromsamehost": "On",
                "challenge": "Random",
                "database": "Responder.db",
                "dns": "Off",
                "dontrespondto": "",
                "dontrespondtoname": "ISATAP",
                "ftp": "On",
                "http": "Off",
                "https": "On",
                "imap": "On",
                "kerberos": "On",
                "ldap": "On",
                "poisonerslog": "Poisoners-Session.log",
                "pop": "On",
                "responderconfigdump": "Config-Responder.log",
                "respondto": "",
                "respondtoname": "",
                "sessionlog": "Responder-Session.log",
                "smb": "On",
                "smtp": "On",
                "sql": "On"
            }
        }
    },
    "paths": {
        "asleap": {
            "bin": "/home/b4cktr4ck/Downloads/eaphammer/local/asleap/asleap"
        },
        "certs": {
            "active_certs_dir": "/home/b4cktr4ck/Downloads/eaphammer/certs/active",
            "active_full_chain": "/home/b4cktr4ck/Downloads/eaphammer/certs/active/fullchain.pem",
            "ca_certs_dir": "/home/b4cktr4ck/Downloads/eaphammer/certs/ca",
            "dh": "/home/b4cktr4ck/Downloads/eaphammer/certs/dh",
            "server_certs_dir": "/home/b4cktr4ck/Downloads/eaphammer/certs/server"
        },
        "dhcp": {
            "script": "/home/b4cktr4ck/Downloads/eaphammer/scripts/dhcp_script.py"
        },
        "directories": {
            "asleap": "/home/b4cktr4ck/Downloads/eaphammer/local/asleap",
            "certs": "/home/b4cktr4ck/Downloads/eaphammer/certs",
            "conf": "/home/b4cktr4ck/Downloads/eaphammer/settings",
            "db": "/home/b4cktr4ck/Downloads/eaphammer/db",
            "hcxdumptool": "/home/b4cktr4ck/Downloads/eaphammer/local/hcxdumptool",
            "hcxtools": "/home/b4cktr4ck/Downloads/eaphammer/local/hcxtools",
            "hostapd": "/home/b4cktr4ck/Downloads/eaphammer/local/hostapd-eaphammer/hostapd",
            "local": "/home/b4cktr4ck/Downloads/eaphammer/local",
            "log": "/home/b4cktr4ck/Downloads/eaphammer/logs",
            "loot": "/home/b4cktr4ck/Downloads/eaphammer/loot",
            "responder": "/home/b4cktr4ck/Downloads/eaphammer/local/Responder",
            "root": "/home/b4cktr4ck/Downloads/eaphammer",
            "saves": "/home/b4cktr4ck/Downloads/eaphammer/saved-configs",
            "scripts": "/home/b4cktr4ck/Downloads/eaphammer/scripts",
            "tmp": "/home/b4cktr4ck/Downloads/eaphammer/tmp",
            "wordlists": "/home/b4cktr4ck/Downloads/eaphammer/wordlists"
        },
        "dnsmasq": {
            "conf": "/home/b4cktr4ck/Downloads/eaphammer/tmp/dnsmasq-2019-11-14-12-44-03-c2EuDrEa6iDM0iuNnGZ1ubExD3JbZhux.conf",
            "log": "/home/b4cktr4ck/Downloads/eaphammer/logs/dnsmasq.log"
        },
        "eap_spray": {
            "log": "/home/b4cktr4ck/Downloads/eaphammer/logs/eap_spray.log"
        },
        "hcxdumptool": {
            "bin": "/home/b4cktr4ck/Downloads/eaphammer/local/hcxdumptool/hcxdumptool",
            "filter": "/home/b4cktr4ck/Downloads/eaphammer/tmp/hcxdumptool-filter-2019-11-14-12-44-03-gSwg306OdaW4EaXCiED38cS7p5KyEU90.txt",
            "ofile": "/home/b4cktr4ck/Downloads/eaphammer/tmp/hcxdumptool-output-2019-11-14-12-44-03-aBOv0ggcnayPSAKdzVT8wTGW09VrK7SA.txt"
        },
        "hcxtools": {
            "hcxpcaptool": {
                "bin": "/home/b4cktr4ck/Downloads/eaphammer/local/hcxtools/hcxpcaptool",
                "ofile": "/home/b4cktr4ck/Downloads/eaphammer/tmp/hcxpcaptool-output-2019-11-14-12-44-03-qFmXQbRXfS1B8X2B94RWue2zg19s6NcX.txt"
            }
        },
        "hostapd": {
            "bin": "/home/b4cktr4ck/Downloads/eaphammer/local/hostapd-eaphammer/hostapd/hostapd-eaphammer",
            "conf": "/home/b4cktr4ck/Downloads/eaphammer/tmp/hostapd-2019-11-14-12-44-03-EBolgoDywMUcBfl5ChlLfj9IXDiJikzO.conf",
            "eap_user": "/home/b4cktr4ck/Downloads/eaphammer/tmp/2019-11-14-12-44-03-ax50CRPwq1ADyjsEIp3vh3bCmAMtMOJy.eap_user",
            "eap_user_header": "/home/b4cktr4ck/Downloads/eaphammer/db/eap_user.header",
            "fifo": "/home/b4cktr4ck/Downloads/eaphammer/tmp/2019-11-14-12-44-03-U8XbCRgDYMLFCb1W5JZZ35exRnoFV2x8.fifo",
            "known_ssids": "/home/b4cktr4ck/Downloads/eaphammer/tmp/2019-11-14-12-44-03-gxNRnCRiGUb68iQWdvTOn2SxR2A0NsbS.known_ssids",
            "lib": "/home/b4cktr4ck/Downloads/eaphammer/local/hostapd-eaphammer/hostapd/libhostapd-eaphammer.so",
            "log": "/home/b4cktr4ck/Downloads/eaphammer/logs/hostapd-eaphammer.log",
            "mac_blacklist": "/home/b4cktr4ck/Downloads/eaphammer/tmp/2019-11-14-12-44-03-s7ipDnG7bcNkRh51U7CDo8Ry7Qr2Zihs.deny",
            "mac_whitelist": "/home/b4cktr4ck/Downloads/eaphammer/tmp/2019-11-14-12-44-03-HdTqbx9Gl8KqCiSFh02MHcRrtfm4ipLh.accept",
            "phase1_accounts": "/home/b4cktr4ck/Downloads/eaphammer/db/phase1.accounts",
            "phase2_accounts": "/home/b4cktr4ck/Downloads/eaphammer/db/phase2.accounts",
            "save": "/home/b4cktr4ck/Downloads/eaphammer/saved-configs/hostapd-2019-11-14-12-44-03-EBolgoDywMUcBfl5ChlLfj9IXDiJikzO.conf",
            "ssid_blacklist": "/home/b4cktr4ck/Downloads/eaphammer/tmp/2019-11-14-12-44-03-EQu8xxHKZIr1tSdDTvnIe3ZSnPV6JgTD.deny",
            "ssid_whitelist": "/home/b4cktr4ck/Downloads/eaphammer/tmp/2019-11-14-12-44-03-KeGCaKh0rtqy6l3W3qEA5QHHH0UjMMgw.accept"
        },
        "openssl": {
            "bin": "/home/b4cktr4ck/Downloads/eaphammer/local/openssl/local/bin/openssl"
        },
        "psk": {
            "psk_capture_file": "/home/b4cktr4ck/Downloads/eaphammer/loot/wpa_handshake_capture-2019-11-14-12-44-03-y11zaCZPud4kvJPQoFEzvBXqiVLpBlB7.hccapx"
        },
        "responder": {
            "analyzer_log": "/home/b4cktr4ck/Downloads/eaphammer/logs/Analyzer-Session.log",
            "bin": "/home/b4cktr4ck/Downloads/eaphammer/local/Responder/Responder.py",
            "cert": "/home/b4cktr4ck/Downloads/eaphammer/local/Responder/certs/responder.crt",
            "conf": "/home/b4cktr4ck/Downloads/eaphammer/local/Responder/Responder.conf",
            "config_log": "/home/b4cktr4ck/Downloads/eaphammer/logs/Config-Responder.log",
            "db": "/home/b4cktr4ck/Downloads/eaphammer/db/Responder.db",
            "exe": "/home/b4cktr4ck/Downloads/eaphammer/local/Responder/files/BindShell.exe",
            "html": "/home/b4cktr4ck/Downloads/eaphammer/local/Responder/files/AccessDenied.html",
            "key": "/home/b4cktr4ck/Downloads/eaphammer/local/Responder/certs/responder.key",
            "poisoners_log": "/home/b4cktr4ck/Downloads/eaphammer/logs/Poisoners-Session.log",
            "session_log": "/home/b4cktr4ck/Downloads/eaphammer/logs/Responder-Session.log"
        }
    }
}
[debug] Options:
{
    "advanced_help": false,
    "algorithm": "sha256",
    "auth": "wpa-eap",
    "auth_alg": null,
    "autocrack": false,
    "beacon_interval": null,
    "bootstrap": false,
    "bssid": null,
    "ca_cert": null,
    "ca_key": null,
    "ca_key_passwd": null,
    "captive_portal": false,
    "capture_wpa_handshakes": null,
    "cert_wizard": false,
    "channel": 4,
    "channel_width": null,
    "cloaking": null,
    "cn": null,
    "country": null,
    "debug": true,
    "dh_file": null,
    "disable_tx_stbc": false,
    "driver": null,
    "dsss_cck_40": false,
    "dtim_period": null,
    "eap_methods_phase_1": "PEAP,TTLS,TLS,FAST",
    "eap_methods_phase_2": "GTC,TTLS-PAP,MD5,TTLS-CHAP,TTLS-MSCHAP,MSCHAPV2,TTLS-MSCHAPV2,TTLS",
    "eap_spray": false,
    "eap_user_file": null,
    "email": null,
    "essid": "CorpWifi",
    "fragm_threshold": null,
    "greenfield": false,
    "hostile_portal": false,
    "ht40": null,
    "ht_delayed_block_ack": false,
    "hw_mode": null,
    "interface": "wlan1",
    "interface_pool": null,
    "karma": false,
    "key_length": 2048,
    "known_beacons": false,
    "known_ssids": null,
    "known_ssids_file": null,
    "ldpc": false,
    "locale": null,
    "loud": false,
    "lsig_txop_prot": false,
    "mac_blacklist": null,
    "mac_whitelist": null,
    "manual_config": null,
    "max_num_stations": null,
    "max_spatial_streams": null,
    "negotiate": "balanced",
    "not_after": 94608000,
    "not_before": 0,
    "obss_interval": null,
    "org": null,
    "org_unit": null,
    "owe_transition_bssid": null,
    "owe_transition_ssid": null,
    "password": null,
    "peap_version": null,
    "pivot": false,
    "pmf": null,
    "pmkid": false,
    "private_key": null,
    "private_key_passwd": null,
    "psk_capture_file": null,
    "reap_creds": true,
    "remote_rig": null,
    "require_ht": false,
    "rts_threshold": null,
    "save_config": null,
    "save_config_only": null,
    "self_signed": false,
    "server_cert": null,
    "short_gi": false,
    "smps": null,
    "ssid_blacklist": null,
    "ssid_whitelist": null,
    "state": null,
    "troll_defender": false,
    "use_max_a_msdu_length": false,
    "user_list": null,
    "wmm": false,
    "wordlist": "/home/b4cktr4ck/Downloads/eaphammer/wordlists/rockyou.txt",
    "wpa_passphrase": null,
    "wpa_version": null
}
[*] Saving current iptables configuration...
[*] Reticulating radio frequency splines...

[*] Using nmcli to tell NetworkManager not to manage wlan1...

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.00s/it]

[*] Success: wlan1 no longer controlled by NetworkManager.
{
    "phase1": {
        "balanced": "PEAP,TTLS,TLS,FAST",
        "speed": "PEAP,TTLS,TLS,FAST",
        "gtc_downgrade": "PEAP",
        "weakest": "PEAP,TTLS,TLS,FAST"
    },
    "phase2": {
        "balanced": "GTC,MSCHAPV2,TTLS-MSCHAPV2,TTLS,TTLS-CHAP,TTLS-PAP,TTLS-MSCHAP,MD5",
        "speed": "MSCHAPV2,TTLS-MSCHAPV2,TTLS,TTLS-CHAP,GTC,TTLS-PAP,TTLS-MSCHAP,MD5",
        "gtc_downgrade": "GTC",
        "weakest": "GTC,TTLS-PAP,MD5,TTLS-CHAP,TTLS-MSCHAP,MSCHAPV2,TTLS-MSCHAPV2,TTLS"
    },
    "peap_version": {
        "gtc_downgrade": "1"
    }
}
[EAPUserFile] phase 1 methods: "PEAP,TTLS,TLS,FAST"
[EAPUserFile] phase 2 methods: "GTC,MSCHAPV2,TTLS-MSCHAPV2,TTLS,TTLS-CHAP,TTLS-PAP,TTLS-MSCHAP,MD5"
[EAPUserFile] phase 1 methods line: *	PEAP,TTLS,TLS,FAST
[EAPUserFile] phase 2 methods line: "t"	GTC,MSCHAPV2,TTLS-MSCHAPV2,TTLS,TTLS-CHAP,TTLS-PAP,TTLS-MSCHAP,MD5	"t" [2]
[EAPUserFile] header file path: /home/b4cktr4ck/Downloads/eaphammer/db/eap_user.header
[EAPUserFile] phase1 accounts file path: /home/b4cktr4ck/Downloads/eaphammer/db/phase1.accounts
[EAPUserFile] phase2 accounts file path: /home/b4cktr4ck/Downloads/eaphammer/db/phase2.accounts
[EAPUserFile] Writing to: /home/b4cktr4ck/Downloads/eaphammer/tmp/2019-11-14-12-44-03-ax50CRPwq1ADyjsEIp3vh3bCmAMtMOJy.eap_user
[*] WPA handshakes will be saved to /home/b4cktr4ck/Downloads/eaphammer/loot/wpa_handshake_capture-2019-11-14-12-44-03-y11zaCZPud4kvJPQoFEzvBXqiVLpBlB7.hccapx

[debug] HostapdConf:
{
    "eap": {
        "capture_wpa_handshakes": "0",
        "dh_file": "/home/b4cktr4ck/Downloads/eaphammer/certs/dh",
        "eap_fast_a_id": "101112131415161718191a1b1c1d1e1f",
        "eap_fast_a_id_info": "hostapd-wpe",
        "eap_fast_prov": "3",
        "eap_server": "1",
        "eap_user_file": "/home/b4cktr4ck/Downloads/eaphammer/tmp/2019-11-14-12-44-03-ax50CRPwq1ADyjsEIp3vh3bCmAMtMOJy.eap_user",
        "eaphammer_logfile": "/home/b4cktr4ck/Downloads/eaphammer/logs/hostapd-eaphammer.log",
        "ieee8021x": "1",
        "pac_key_lifetime": "604800",
        "pac_key_refresh_time": "86400",
        "pac_opaque_encr_key": "000102030405060708090a0b0c0d0e0f",
        "private_key": "/home/b4cktr4ck/Downloads/eaphammer/certs/active/fullchain.pem",
        "psk_capture_file": "/home/b4cktr4ck/Downloads/eaphammer/loot/wpa_handshake_capture-2019-11-14-12-44-03-y11zaCZPud4kvJPQoFEzvBXqiVLpBlB7.hccapx",
        "server_cert": "/home/b4cktr4ck/Downloads/eaphammer/certs/active/fullchain.pem",
        "wpa_key_mgmt": "WPA-EAP"
    },
    "general": {
        "autocrack_fifo_path": "/home/b4cktr4ck/Downloads/eaphammer/tmp/2019-11-14-12-44-03-U8XbCRgDYMLFCb1W5JZZ35exRnoFV2x8.fifo",
        "beacon_int": "100",
        "bssid": "00:11:22:33:44:00",
        "channel": 4,
        "country_code": "US",
        "ctrl_interface": "./run/hostapd-control-interface",
        "ctrl_interface_group": "0",
        "dtim_period": "1",
        "fragm_threshold": "2346",
        "hw_mode": "g",
        "ieee80211w": "0",
        "ignore_broadcast_ssid": "0",
        "interface": "wlan1",
        "known_beacons": "0",
        "logger_stdout": "-1",
        "logger_stdout_level": "2",
        "logger_syslog": "-1",
        "logger_syslog_level": "2",
        "loud_karma": "0",
        "max_num_sta": "255",
        "rts_threshold": "2347",
        "ssid": "CorpWifi",
        "use_autocrack": "0",
        "use_karma": "0"
    },
    "wpa": {
        "auth_algs": "3",
        "wpa": "2",
        "wpa_pairwise": "TKIP CCMP"
    }
}

[hostapd] AP starting...

random: Trying to read entropy from /dev/random
Configuration file: /home/b4cktr4ck/Downloads/eaphammer/tmp/hostapd-2019-11-14-12-44-03-EBolgoDywMUcBfl5ChlLfj9IXDiJikzO.conf
ctrl_interface_group=0
Line 24: unknown configuration item 'loud_karma'
Line 25: unknown configuration item 'known_beacons'
Line 47: unknown configuration item 'capture_wpa_handshakes'
Line 48: unknown configuration item 'psk_capture_file'
4 errors found in configuration file '/home/b4cktr4ck/Downloads/eaphammer/tmp/hostapd-2019-11-14-12-44-03-EBolgoDywMUcBfl5ChlLfj9IXDiJikzO.conf'
Failed to set up interface with /home/b4cktr4ck/Downloads/eaphammer/tmp/hostapd-2019-11-14-12-44-03-EBolgoDywMUcBfl5ChlLfj9IXDiJikzO.conf
hostapd_init: free iface 0x7f72d0002ce0
Failed to initialize interface

**EAPHammer Version (./eaphammer --version)**

1.12.0 (I also get unknown option: --version)

**OS (the OS from which you are running EAPHammer)**

Parrot OS

**Configuration of Target Access Point (if known / applicable)**

N/A

**Configuration of Target Client Device (if known / applicable)**

N/A

**Additional context**

I think hostapd-eaphammer might be the issue. I attempt to install and compile the version in local/eaphammer and I get the following errors:

../src/ap/wpa_auth.c: In function ‘wpa_receive’:
../src/ap/wpa_auth.c:1041:26: error: ‘struct wpa_auth_config’ has no member named ‘ssid_len’
 1041 |    fwrite(&wpa_auth->conf.ssid_len,1,1,psk_cap_file);
      |                          ^
../src/ap/wpa_auth.c:1042:25: error: ‘struct wpa_auth_config’ has no member named ‘ssid’
 1042 |    fwrite(wpa_auth->conf.ssid,32,1,psk_cap_file);
      |                         ^
../src/ap/wpa_auth.c:1066:30: warning: passing argument 1 of ‘WPA_GET_BE16’ from incompatible pointer type [-Wincompatible-pointer-types]
 1066 |    fwrite(key+1,WPA_GET_BE16(&key_data_length),1,psk_cap_file);
      |                              ^~~~~~~~~~~~~~~~
      |                              |
      |                              u16 * {aka short unsigned int *}
In file included from ../src/ap/wpa_auth.c:11:
/home/b4cktr4ck/Downloads/eaphammer/local/hostapd-eaphammer/src/utils/common.h:213:42: note: expected ‘const u8 *’ {aka ‘const unsigned char *’} but argument is of type ‘u16 *’ {aka ‘short unsigned int *’}
  213 | static inline u16 WPA_GET_BE16(const u8 *a)
      |                                ~~~~~~~~~~^
make: *** [Makefile:1301: ../src/ap/wpa_auth.o] Error 1

Not sure though.

**Comment by s0lst1c3** [comment]
Hi @b4cktr4ck2, can you please run the following command and post the output?

```
uname -a
```

**Comment by b4cktr4ck2** [comment]
Absolutely @s0lst1c3 , my bad. Output below:

Linux hostname_here 4.19.0-parrot1-13t-amd64 #1 SMP Debian 4.19.13-1parrot1.13t (2019-01-09) x86_64 GNU/Linux

**Comment by s0lst1c3** [comment]
Is that Parot OS?

**Comment by b4cktr4ck2** [comment]
Yes correct.

**Comment by b4cktr4ck2** [comment]
Quick update- that binary for hostapd (/home/b4cktr4ck/Downloads/eaphammer/local/hostapd-eaphammer/hostapd/hostapd-eaphammer) doesn't exist. I wonder if it's calling an old version of hostapd?

**Comment by b4cktr4ck2** [comment]
Ah-ha. Attempting to compile the hostapd that comes bundled with this project returns the following when running kali-setup:

/usr/bin/ld: main.o: relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make: *** [Makefile:1339: hostapd-eaphammer_lib] Error 1

**Comment by b4cktr4ck2** [comment]
After one dist-upgrade, one kernel issue, one re-installation of the 8812au driver, and a complete wipe/reinstall of eaphammer, it's now working on the newest version. The issue seems to have been with a missing intel-microcode package, though that's just a guess.

Closing the issue, and my eyes after 8 hours of debugging.

**Comment by s0lst1c3** [comment]
Thanks for all of your hard work. If you don't mind, could you possibly document what you did,  including any dependencies that you had to install? Right now the only "officially" supported version is Kali, but that's mainly because I haven't had the time to make reliable build scripts for other operating systems. There's an incoming pull request for Ubuntu 18.04 that looks pretty solid (see: #120), and I'm currently working on Ubuntu 19.10 (although this is proving to be painful). Parot OS is on my radar as well.

**Comment by s0lst1c3** [comment]
Also if you feel like writing a build script, that'd be awesome too. :)

**Comment by b4cktr4ck2** [comment]
I can definitely try my best in terms of documentation + a build script, though a build script will take me a bit more time to put together and flesh out. 

Do you have a preference for how I document the process? Should I just throw it into a message here or make a pull request with a README, or via a private message?

**Comment by s0lst1c3** [comment]
Message here works, doesn’t have to be anything fancy. I’m planning on pushing some build scripts this weekend and will try to get one written for Parot. When I’ll do, I’ll just reference this issue in the pull request to tie everything together. Appreciate the help!

**Comment by b4cktr4ck2** [comment]
I didn't forget! I've put together a high level list of steps I took on the latest Limux kernel, 5.3.0:

1. Installed dependencies. They are below:
sudo apt-get install git python3 python3-setuptools python3-pip build-essential libpcap-dev aircrack-ng pixiewps dkms
sudo apt-get remove realtek-rtl88xxau-dkms

2. Ran a git clone:
git clone https://github.com/aircrack-ng/rtl8812au.git <-- I couldn't get default RTL8812AU drivers to work, had to get em from here.
cd rtl8812au
sudo ./dkms-install.sh
make
sudo make install 
sudo modprobe -v 88XXau.ko

3. That didn't work for me, if it does for you awesome, but if it doesn't here's my workaround- you need to copy the kernel module into a directory and update the dependency file:
sudo cp 88XXau.ko /lib/modules/$(uname -r)/
sudo nano /lib/modules/5.3.0-1parrot1-amd64/modules.dep
I guess I added these lines:
updates/dkms/wl.ko: kernel/net/wireless/cfg80211.ko kernel/net/rfkill/rfkill.ko
updates/88XXau.ko: kernel/net/wireless/cfg80211.ko kernel/net/rfkill/rfkill.ko kernel/drivers/usb/core/usbcore.ko kernel/drivers/usb/common/usb-common.ko
^^this second one is all one line

4. Time to install eaphammer. NOTE: I couldn't get my original install to work, so I moved everything to a backup directory and ran the following:
git clone https://github.com/s0lst1c3/eaphammer.git
cd eaphammer
sudo ./kali-setup
I then rebooted and it worked. Hopefully this helps a bit. There's also a guide I'm going to try and track down that I used.
