### ISSUE TITLE
ImportError: No module named 'pem'

### ISSUE THREAD

**Issue by hackvice** [s0lst1c3/eaphammer#130]
**Describe the bug**
Import error

**To Reproduce**
Normal install

1. ...Install
2. ...enerate certificates
3. ...ImportError: No module named 'pem'
4. ... unprofit :dagger: 

**Expected behavior**
Install

**Screenshots**
**Command string(s) used**

```
> ./eaphammer --cert-wizard
> ./eaphammer
```

**EAPHammer verbose output (using the --debug flag)**

```
./eaphammer --cert-wizard
Traceback (most recent call last):
  File "./eaphammer", line 4, in <module>
    import cert_wizard
  File "/home/user/eaphammer/cert_wizard/__init__.py", line 1, in <module>
    from cert_wizard.core import import_cert
  File "/home/user/eaphammer/cert_wizard/core.py", line 1, in <module>
    import cert_wizard.cert_utils as cert_utils
  File "/home/user/eaphammer/cert_wizard/cert_utils.py", line 3, in <module>
    import pem
ImportError: No module named 'pem'
```

**EAPHammer Version (./eaphammer --version)**
```
./eaphammer --version
Traceback (most recent call last):
  File "./eaphammer", line 4, in <module>
    import cert_wizard
  File "/home/user/eaphammer/cert_wizard/__init__.py", line 1, in <module>
    from cert_wizard.core import import_cert
  File "/home/user/eaphammer/cert_wizard/core.py", line 1, in <module>
    import cert_wizard.cert_utils as cert_utils
  File "/home/user/eaphammer/cert_wizard/cert_utils.py", line 3, in <module>
    import pem
ImportError: No module named 'pem'

```

**OS (the OS from which you are running EAPHammer)**
Parrot OS/Kali 

**Configuration of Target Access Point (if known / applicable)**
**Configuration of Target Client Device (if known / applicable)**
**Additional context**

Tried using` python3 -m install pem` same issue...
Tried using `sudo python3.7 -m pip install pem` same issue...
Tried using `sudo python3 -m pip install pem` Same issue...

**Comment by kmackinley** [comment]
Try:

apt install python3-pip
pip3 install pem

Do the same "pip3 install" command for additional modules that might be missing.

**Comment by 7XGVaXhzDFZgw7vhw3fmluovhUF7bj5vIY4gjW7** [comment]
@s0lst1c3 can @kmackinley comment this be appended to the ./kali-setup script and/or documentation.

**Comment by s0lst1c3** [comment]
@7XGVaXhzDFZgw7vhw3fmluovhUF7bj5vIY4gjW7  Yep. I should have some time later this week to iron a lot of this stuff out. It looks like a lot of people are using Parot OS so that's something that I definitely want to start supporting in an official capacity soon.

**Comment by 7XGVaXhzDFZgw7vhw3fmluovhUF7bj5vIY4gjW7** [comment]
All good, im actually on a fresh install of the newest kali 2019.4 "5.4.0-kali2-amd64" and was getting the same error. love this tool keep up the great work!

**Comment by Soutcast** [comment]
I had the same error and i solved it by running
`pip3 install pem`
as root

**Comment by DroidKali** [comment]
I'm using Kali 2020.4 as the same error，how to fix it？

**Comment by vader-gif** [comment]
run python3 eaphammer instead of ./eaphammer

**Comment by binary1985** [comment]
> run python3 eaphammer instead of ./eaphammer

This worked for me

**Comment by Kinny092** [comment]
python3 eaphammer works for me too but does bashing a python script work? hmmm
