### ISSUE TITLE
version 1.12.1 with --autocrack doesn't add creds to the database

### ISSUE THREAD

**Issue by GobNobber** [s0lst1c3/eaphammer#140]
**Describe the bug**
Using version 1.12.1 on Kali the --autocrack correctly adds the user and pass to the temporary eap_user file, however:
1.) they aren't active and don't work from the temp file
2.) they aren't saved to the ./db/phase2.account file
3.) if they are manually copied to the ./db/phase2.account file and eaphammer is restarted, the credentials are added automatically to the ./tmp/*.eap_user file and . . . . THEY WORK!!!

Thus is seams that 
1.) captured creds aren't saving to the database
2.) dynamically adding new entries to the temp file doesn't do anything.  they have to be there when the service starts up.  guessing they are loaded into memory and there needs to be a loop of some kind to check the file routinely or something

**To Reproduce**

1. Start up with something like ./eaphammer -i wlan0 --channel 1 --auth wpa-eap --essid ESSID --autocrack --wordlist wordlists/rockyou.txt --
2. connect to ESSID with user:user1 pass:Password123
3. validate that creds show up in ./tmp/*.eap_user
4. try creds again . . . they should fail
5. exit nicely by pressing enter
6. restart service.  check ./tmp/*.eap_user . . .  .creds are not there
7. try to connect to ESSID again . . . still fails
8. add creds to ./db/phase2.account with the correct format
9. stop and start eaphammer
10. creds are now in the ./tmp/*.eap_user file
11. try to connect, creds work

**Expected behavior**

Based on the autocrack section, this should be dynamic and work at least almost instantly with a basic password or at least when trying a second time.  They don't because there is some sort of issue picking up the creds from the temp file

**OS (the OS from which you are running EAPHammer)**

Kali (updated today . . . . had the problem before the update as well)

**Configuration of Target Access Point (if known / applicable)**

stock

**Configuration of Target Client Device (if known / applicable)**

Windows 10, samsung note 9, Kindle Fire . . . all do the same thing

**Comment by s0lst1c3** [comment]
This is known but undocumented behavior that has to do with the fact that hostapd loads creds into memory on startup. Fixing this issue would require dramatic changes to hostapd's codebase, which would be difficult to implement and maintain. EAPHammer's documentation has been updated to reflect this behavior.
