### ISSUE TITLE
libhostapd-eaphammer.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Al-gore-ithm** [s0lst1c3/eaphammer#141]
Hi,
I'm trying to experiment with eaphammer, all compiled using the setup script using Kali 2020.1b. When I try to run I get the following output with error:
[*] Checking for rootness...
[*] I AM ROOOOOOOOOOOOT
[*] Root privs confirmed! 8D
[*] Saving current iptables configuration...
[*] Reticulating radio frequency splines...

[*] Using nmcli to tell NetworkManager not to manage wlan0...

100%|█████████████████████████████████████████| 1/1 [00:01<00:00,  1.00s/it]

[*] Success: wlan0 no longer controlled by NetworkManager.
[*] WPA handshakes will be saved to /home/al/eaphammer/loot/wpa_handshake_capture-2020-04-25-15-00-10-V43NtX8lvrlIOIILAsm9w23GLBWnAvL5.hccapx
Traceback (most recent call last):
  File "./eaphammer", line 835, in <module>
    reap_creds()
  File "./eaphammer", line 497, in reap_creds
    hostapd.start()
  File "/home/al/eaphammer/core/hostapd.py", line 40, in start
    self.libhostapd = ctypes.cdll.LoadLibrary(self.lib_path)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
**OSError: /home/al/eaphammer/local/hostapd-eaphammer/hostapd/libhostapd-eaphammer.so: cannot open shared object file: No such file or directory**

What am I missing (aside libhost-eaphammer.so), and how do I fix it?

Thanks in advance.

Al

**Comment by Al-gore-ithm** [comment]
Any suggestions? Anyone.... Please.

**Comment by kmackinley** [comment]
Were there any errors when running the setup script? Particularly when compiling hostapd?

**Comment by W00t3k** [comment]
Alt-gore-ithm.

It's your SSL configuration. Gabriel talks about how that has all changed
due to them fixing the broken SSL in the older Linux distros. Try fixing it
locally - or trying another build of Linux to test that theory.

**Comment by Al-gore-ithm** [comment]
Thanks for replying. 

Setup script ran without apparent issue.

**Comment by Al-gore-ithm** [comment]
I have no idea what happened, no warnings or errors during install; a complete rebuild of the kali distro followed by a new install has worked. Not what I wanted to do, but its solved my issue.

kmackinley - thanks for the interest.

Onward and upward...

**Comment by yildizberat** [comment]
you can use just `./kali-setup` command during setup. If you can use `python3 ./kali-setup`, its may give an error
