### ISSUE TITLE
No such file libhostapd-eaphammer.so

### ISSUE THREAD

**Issue by mirhmousavi** [s0lst1c3/eaphammer#146]
I got this error
`
OSError: eaphammer/local/hostapd-eaphammer/hostapd/libhostapd-eaphammer.so: cannot open shared object file: No such file or directory
`

**Comment by developer3000S** [comment]
Please, start: 
sudo ./kali-setup

**Comment by ertaku12** [comment]
issue is up again!

**Comment by JustDinooo** [comment]
Any update?
