### ISSUE TITLE
Missing python package 'flask_cors'

### ISSUE THREAD

**Issue by whoot** [s0lst1c3/eaphammer#152]
Cloned the git repo, make update and upgrade and executed kali-setup.
Seems like the python3 package 'flask_cors' is not installed when running the installation.

**To Reproduce**

1. sudo apt -y update
2. sudo apt -y upgrade
3. sudo ./kali-setup
4. ./eaphammer -h

**Screenshots**

![grafik](https://user-images.githubusercontent.com/8066322/98217968-7fad3c80-1f4b-11eb-830e-22fd775fbcd6.png)

**EAPHammer Version (./eaphammer --version)**

Version 1.13.0

**OS (the OS from which you are running EAPHammer)**

Linux kali 5.9.0-kali1-amd64 #1 SMP Debian 5.9.1-1kali2 (2020-10-29) x86_64 GNU/Linux

**Solution**

```python3 -m pip install flask_cors```

**Comment by Craftonix** [comment]
same condition.
installed manually flask_cors with pip

but still have an error :

Traceback (most recent call last):
  File "./eaphammer", line 5, in <module>
    import core.cli
  File "/home/kali/eaphammer/core/__init__.py", line 10, in <module>
    from . import wskeyloggerd
  File "/home/kali/eaphammer/core/wskeyloggerd/__init__.py", line 1, in <module>
    from core.wskeyloggerd.app import run
  File "/home/kali/eaphammer/core/wskeyloggerd/app.py", line 21, in <module>
    from flask_socketio import SocketIO, emit
ModuleNotFoundError: No module named 'flask_socketio'


tryed :
python3 -m pip install flask_socketio
(..)
Successfully installed flask-socketio-4.3.1

but nothing better

**Comment by s0lst1c3** [comment]
Resolved by #153
