### ISSUE TITLE
Could not read interface wlan0 flags: No such device nl80211: Driver does not support authentication/association or connect commands nl80211: deinit ifname=wlan0 disabled_11b_rates=0 Could not read interface wlan0 flags: No such device nl80211 driver initialization failed. wlan0: interface state UNINITIALIZED->DISABLED wlan0: AP-DISABLED  wlan0: CTRL-EVENT-TERMINATING  hostapd_free_hapd_data: Interface wlan0 wasn't started   Press enter to quit...   [hostapd] Terminating event loop... [hostapd] Event loop terminated. [hostapd] AP disabled.  Error: Device 'wlan0' not found.

### ISSUE THREAD

**Issue by 1234SABITH** [s0lst1c3/eaphammer#160]
it say fallowing error continually How Can Fix that Please Give me the Solution....
my Device Configuration..
""""""""""""""""""""""""""""""""""""

└──╼ $uname -a
Linux parrot 5.7.0-2parrot2-amd64 #1 SMP Debian 5.7.10-1parrot2 (2020-07-31) x86_64 GNU/Linux

hostapd-WPE v2.9
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
-----------------------------------------------------
WPE (Wireless Pwnage Edition)
This version has been cleverly modified to target
wired and wireless users.
Twitter: @aircrackng

└──╼ $lsusb
Bus 002 Device 003: ID 0a5c:5801 Broadcom Corp. BCM5880 Secure Applications Processor with fingerprint swipe sensor
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

lo        no wireless extensions.

eth0      no wireless extensions.

wlan0mon  IEEE 802.11  ESSID:"Galaxy J57C6F"  
          Mode:Managed  Frequency:2.437 GHz  Access Point: 34:2D:0D:DA:7C:6F   
          Bit Rate=58.5 Mb/s   Tx-Power=15 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality=48/70  Signal level=-62 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:18   Missed beacon:0

""""""""""""""""""""""""""""""""""""""""""""""
[*] I AM ROOOOOOOOOOOOT
[*] Root privs confirmed! 8D
[*] Saving current iptables configuration...
[*] Reticulating radio frequency splines...
Error: Device 'wlan0' not found.

[*] Using nmcli to tell NetworkManager not to manage wlan0...

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.00s/it]

[*] Success: wlan0 no longer controlled by NetworkManager.
[*] WPA handshakes will be saved to /home/sabith/Desktop/Kali/wifi/eaphammer/loot/wpa_handshake_capture-2020-12-10-13-00-55-yB1ihKmSYdaXH3DkE8LL4MzxtRWbNesm.hccapx

[hostapd] AP starting...

Configuration file: /home/sabith/Desktop/Kali/wifi/eaphammer/tmp/hostapd-2020-12-10-13-00-55-ZOCeB9B7T0tC0waO0vXGfoRgKNNzq6Ud.conf
Could not read interface wlan0 flags: No such device
nl80211: Driver does not support authentication/association or connect commands
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
Could not read interface wlan0 flags: No such device
nl80211 driver initialization failed.
wlan0: interface state UNINITIALIZED->DISABLED
wlan0: AP-DISABLED 
wlan0: CTRL-EVENT-TERMINATING 
hostapd_free_hapd_data: Interface wlan0 wasn't started

Press enter to quit...

[hostapd] Terminating event loop...
[hostapd] Event loop terminated.
[hostapd] AP disabled.

Error: Device 'wlan0' not found.

[*] Using nmcli to give NetworkManager control of wlan0...

**Comment by s0lst1c3** [comment]
Come on dude. Take another look at the output of your `lsusb` command. Is wlan0 really the name of your wireless interface?
