### ISSUE TITLE
No Module named 'pem'

### ISSUE THREAD

**Issue by Thestorm77** [s0lst1c3/eaphammer#166]
Just installed a fresh kali image 2020.4. Cloned the repository and ran the ./kali-setup script. When it was installing you can clearly see that pem requirement was met in the logs, but after the script finished i get the following error 

Traceback (most recent call last):
  File "./eaphammer", line 4, in <module>
    import cert_wizard
  File "/home/kali/eaphammer/cert_wizard/__init__.py", line 1, in <module>
    from cert_wizard.core import import_cert
  File "/home/kali/eaphammer/cert_wizard/core.py", line 1, in <module>
    import cert_wizard.cert_utils as cert_utils
  File "/home/kali/eaphammer/cert_wizard/cert_utils.py", line 3, in <module>
    import pem
ModuleNotFoundError: No module named 'pem'

When runing pip3-install pem it shows that it is installed 

pip3 install pem
Requirement already satisfied: pem in /usr/local/lib/python3.9/dist-packages (20.1.0)

**Comment by rev10d** [comment]
Hey - 
The latest kali defaults to python3.9. You can find the problem in the eaphammer file, line numero uno:

#!/usr/bin/env python3.8

modify that line to 

#!/usr/bin/env python3.9

cheers,
@rev10d

**Comment by s0lst1c3** [comment]
Resolved 1.14.0
