### ISSUE TITLE
EAP User File Flag

### ISSUE THREAD

**Issue by besimaltnok** [s0lst1c3/eaphammer#167]
**Describe the bug**

When I manually define the eap_user file, I get an error. It cannot parse the values I have given.

**To Reproduce**

1. `./eaphammer --interface wlan0 --auth wpa-eap --essid example --creds --eap-user-file 2021-01-31-12-03-49-qnYz4aTzW96Yk9SMXwsZGyMQJZPUHsaz.eap_user`

**Expected behavior**

I was trying to manually define an eap_user file

**Screenshots**

![telegram-cloud-photo-size-4-5816606331765897111-y](https://user-images.githubusercontent.com/4296962/106392637-d66bca80-6403-11eb-8406-03ae03a0b84a.jpg)

**Comment by s0lst1c3** [comment]
Looks like you're missing the phase 1 methods block within the EAP user file.
