### ISSUE TITLE
Replace dsniff with a modern supported alternative

### ISSUE THREAD

**Issue by blshkv** [s0lst1c3/eaphammer#169]
**Is your feature request related to a problem? Please describe.**
dsniff was written back in 2000, 21 years ago. It were no updates since then and each distribution has to patch it with more and more patches every year. Currently, debian has 35 unofficial patches written by random people. These patches fix critical functionality such pcap reading, 64-bit support, segfault, openssl, spoofing and so on. The list is insane.

**Describe the solution you'd like**
Please replace it with a better supported alternative

**Describe alternatives you've considered**
SET (https://github.com/trustedsec/social-engineer-toolkit/) supports both dsniff and ettercap (https://github.com/Ettercap/ettercap)

**Additional context**
We have just removed dsniff from Pentoo and its related functionality is broken

pentoo/pentoo-overlay#700

**Comment by s0lst1c3** [comment]
"The list is insane."

Gotcha. I'm guessing this is making life difficult from a package maintainer's perspective? Good news - I'm pretty sure it's not actually a dependency anymore and simply never made it out of the dependency list for some reason. EAPHammer was originally using it for DNS redirection but I'm almost positive that we either leverage responder or native solutions for this now.  I'll need to verify this and run testing before removing it though.

Also, if you could please use one of the existing issue templates next time it would be greatly appreciated. Makes it easier on me to track things in a consistent way. Thanks.

**Comment by blshkv** [comment]
I have fixed the template. Thanks!

**Comment by s0lst1c3** [comment]
Retired in favor of DNSMasq
