### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [s0lst1c3/eaphammer#182]
Hi there,

I couldn't find a `SECURITY.md` in your repository and am not sure how to best contact you privately to disclose a security issue.

Can you add a `SECURITY.md` file with an e-mail to your repository, so that our system can send you the vulnerability details? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, you should receive an e-mail within the next hour with more info.

Thanks! (cc @huntr-helper)

**Comment by s0lst1c3** [comment]
Hey Jamie,

Thanks for reaching out. Just send it to ***@***.*** and I’ll follow up with you.

**Comment by JamieSlome** [comment]
@s0lst1c3 - is this a valid e-mail address? (***@***.***)

**Comment by s0lst1c3** [comment]
Hmm. Looks like GitHub is censoring email addresses. I guess just hit me up on Twitter. My DMs are open.

https://twitter.com/s0lst1c3

**Comment by JamieSlome** [comment]
Found e-mail on your website - refer to https://github.com/s0lst1c3/eaphammer/pull/183

**Comment by JamieSlome** [comment]
Otherwise, you can access the advisory directly:

https://huntr.dev/bounties/d0e7ccb9-95f3-459e-99bc-7be3bfd8ed3e/

It is private to you and the discloser.

**Comment by s0lst1c3** [comment]
For the sake of transparency, you can escape out of EAPHammer and back into the terminal that launched it by using the --interface flag. 

`#!/bin/bash
python3 ./eaphammer --interface ';touch example' `

It's clever, but there really isn't any impact here from a security standpoint. Closing as not a bug.
