### ISSUE TITLE
nl80211 annoy..

### ISSUE THREAD

**Issue by ska-la** [s0lst1c3/eaphammer#185]
**Describe the bug**
When using option --driver with other than "nl80211" value

**To Reproduce**

$ sudo ./eaphammer -i wlan0 ... --driver (hostap/none) --debug

**Expected behavior**

Still a messages are seen with the prefix "nl80211:" Why?

**Screenshots**
...
nl80211: ifindex-4
nl80211: beacon_int=100
nl80211: beacon_rate=0
nl80211: rate_type=0
nl80211: dtim_period=1
nl80211: ssid=test0
.... and so on ...

**Command string(s) used**

$ sudo ./eaphammer -i wlan0 -e test0 --karma --known-beacons --known-ssids test1 test2 test3 --driver hostap --debug

**EAPHammer Version (./eaphammer --version)**

1.13.5

**OS (the OS from which you are running EAPHammer)**

Kali 2021.2

**Configuration of Target Access Point (if known / applicable)**

Fill this in if possible.

**Configuration of Target Client Device (if known / applicable)**

Fill this in if possible.

**Additional context**

Use client device with driver 88XXau.ko (Realtek)
As the driver doesn't support nl80211 commands (don't send a fake beacons), possibly it will work with another hostap driver.

**Comment by s0lst1c3** [comment]
Don’t use Realtek for Wi-Fi pentesting… annoy lol
