### ISSUE TITLE
EapHammer is not collecting credentials - WPA2 Enterprise

### ISSUE THREAD

**Issue by B4RD4k** [s0lst1c3/eaphammer#186]
Hello Eaphammer dev team.

I'm experiencing a failure to collect user credentials when using the following command, and this device ALFA AWUS036NHR v2:

`sudo ./eaphammer --bssid xx:xx:xx:xx:xx:xx --essid BLA-WiFi --channel 2 --auth wpa-eap --interface wlan0 --negotiate weakest --creds `

But when changing the device to TP Link TL-WN722N everything is working smoothly and I can capture credentials again.

Running on Kali Linux in VirtualBox.
The drivers are properly set since I can see in iwconfig both of the devices.

If any additional data is needed, please ask and I'll provide.

Thanks for the genius tool made for the community.

**Comment by s0lst1c3** [comment]
Wireless interfaces in Linux can run in three modes:
- managed mode - Used to connect to wireless networks as a station (aka client). When in this mode your interface acts as a transmitter and receiver paired to a specific SSID.
- monitor mode - Used to passively listen to nearby wireless traffic. Your interface acts as a promiscuous receiver, and can be used to transmit to arbitrary SSIDs (I.e packet injection).
- master mode - Your interface acts as an access point. It can transmit and receive packets from stations (clients) that have associated with it.


The ALFA AWUS036NHR v2 doesn’t support master mode, which means you can’t use it to create an access point. Hence why the command is failing.

Cheers.

**Comment by s0lst1c3** [comment]
> Thanks for the genius tool made for the community.

I don’t know about “genius” haha, I think that’s a bit strong, but thanks.
