### ISSUE TITLE
hostapd_free_hapd_data: Interface wlan0 wasn't started

### ISSUE THREAD

**Issue by Lucifer1993** [s0lst1c3/eaphammer#189]
when I use eaphammer to execute command,it's exception down. how to deal with it? my os is kali

[?] Am I root?
[*] Checking for rootness...
[*] I AM ROOOOOOOOOOOOT
[*] Root privs confirmed! 8D
[*] Saving current iptables configuration...
[*] Reticulating radio frequency splines...

[*] Using nmcli to tell NetworkManager not to manage wlan1...

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.00s/it]

[*] Success: wlan1 no longer controlled by NetworkManager.
[*] WPA handshakes will be saved to /var/lib/eaphammer/loot/wpa_handshake_capture-2021-11-12-09-17-58-n7bingOg1XNf2F4noP7tNDZXPpeVjzwz.hccapx

Configuration file: /var/lib/eaphammer/tmp/hostapd-2021-11-12-09-17-58-3UtjbPIi3l9yCfF3xM7jRAiZnDESZI6O.conf
[hostapd] AP starting...

mkdir[ctrl_interface]: No such file or directory
Failed to setup control interface for wlan1
wlan1: Unable to setup interface.
wlan1: interface state UNINITIALIZED->DISABLED
wlan1: AP-DISABLED
wlan1: CTRL-EVENT-TERMINATING
hostapd_free_hapd_data: Interface wlan1 wasn't started
nl80211: deinit ifname=wlan1 disabled_11b_rates=0

**Comment by williamcaput** [comment]
I'm getting the same error.
Installed eaphammer using the install script on an updated version of Kali.
Any help is appreciated.

**Comment by 0x6d6f7468** [comment]
Hey folks, I just had a similar error on a Kali box but found that running from source fixed the issue. The latest version of the code handles pathing better in settings/paths.py.

Interestingly, the EAPHammer version installed on this Kali box is reportedly 1.13.5, which should be the latest, but the paths.py file is older. Not sure what's up with that, but running from source definitely seems to fix the configuration file path issues.

**Comment by breachr** [comment]
This is super unclean, but if you still want to use the cli parameters with packaged version and dont rely on manual config you can prepend a slash in here:

/usr/share/eaphammer/core/hostapd_config.py

-> line 495: 
general_configs['ctrl_interface'] = "/" + settings.dict['paths']['hostapd']['ctrl_interface']

**Comment by s0lst1c3** [comment]
Resolved 1.14.0
