### ISSUE TITLE
Responder settings mismatch

### ISSUE THREAD

**Issue by ecapson** [s0lst1c3/eaphammer#192]
**Describe the bug**
Current Responder settings have mismatch with the latest Responder. Unsupported starting options and missing entries in the config file. 

**To Reproduce**

1. Start evil twin with hostile portal

**Expected behavior**

Responder part of the evil twin won't start

**Screenshots**

![image](https://user-images.githubusercontent.com/19683073/153035772-6f4f6fe6-849a-492a-a728-efff63ed2a0a.png)

**Command string(s) used**

```eaphammer -i wlan0 -c 1 -e test --hostile-portal```

**EAPHammer verbose output (using the --debug flag)**

Unrelated to bug

**EAPHammer Version (./eaphammer --version)**

Latest on master. 
--version no longer exist?

**OS (the OS from which you are running EAPHammer)**

Kali Arm 5.4.83-Re4son-v8l+

**Comment by s0lst1c3** [comment]
Resolved 1.14.0
