### ISSUE TITLE
Is Eaphammer no longer maintained?

### ISSUE THREAD

**Issue by mtnsec** [s0lst1c3/eaphammer#194]
Just wondering if this is the right place to go for bugfixes?  I reported a bug in early 2020 that's still open, and the last time this repository was updated was more than a year ago as well.

Will these bugs be fixed here, or is there a fork I should be looking at instead of this one?

**Comment by s0lst1c3** [comment]
My bad I just woke up. Mildly hungover. What year is it again? Holy shit it's 2023? :D
