### ISSUE TITLE
hcxdumptool wont compile on kali (issue includes kludge fix)

### ISSUE THREAD

**Issue by stuartw1** [s0lst1c3/eaphammer#197]
Newest kali won't compile hcxdumptool as supplied

---
[*] Compiling hcxdumptool...

cc -O3 -Wall -Wextra -std=gnu99  -o hcxdumptool hcxdumptool.c -lpthread 
hcxdumptool.c: In function ‘processpackets’:
hcxdumptool.c:3098:37: error: ‘SIOCGSTAMP’ undeclared (first use in this function); did you mean ‘SIOCGARP’?
 3098 |                 if(ioctl(fd_socket, SIOCGSTAMP , &tv) < 0)
      |                                     ^~~~~~~~~~
      |                                     SIOCGARP
hcxdumptool.c:3098:37: note: each undeclared identifier is reported only once for each function it appears in
hcxdumptool.c: In function ‘processrcascan’:
hcxdumptool.c:3401:37: error: ‘SIOCGSTAMP’ undeclared (first use in this function); did you mean ‘SIOCGARP’?
 3401 |                 if(ioctl(fd_socket, SIOCGSTAMP , &tv) < 0)
      |                                     ^~~~~~~~~~
      |                                     SIOCGARP
make: *** [Makefile:29: build] Error 1

---

this can be fixed quickly (but maybe not the correct way) by adding the following to ./local/hcxdumptool/hcxdumptool.c in the includes section

`#include <linux/sockios.h>`

the file should now compile without errors

**Comment by stuartw1** [comment]
I was about to create a pull request, but has been done already in #196

**Comment by s0lst1c3** [comment]
Resolved 1.14.0
