### ISSUE TITLE
Missing python-tqdm in the Kali Linux dependencies file

### ISSUE THREAD

**Issue by mattbrun** [s0lst1c3/eaphammer#2]
On Kali Linux, after installing the dependencies listed [here](https://github.com/s0lst1c3/eaphammer/blob/master/kali-dependencies.txt), and after executing `python setup.py`, if I try to execute the program I get dependency missing error.

I solved the issue installing `tqdm` library with `sudo apt install python-tqdm`.

Cheers

**Comment by s0lst1c3** [comment]
Thanks for catching this. I've added a Python dependency file to reflect this, as well as instructions on how install Python dependencies using Pip to the README file. Changes will be merged shortly.
