### ISSUE TITLE
Newest version of Kali with all updates fails to run

### ISSUE THREAD

**Issue by PowerPress** [s0lst1c3/eaphammer#200]
**Describe the bug**
Eaphammer installs from git clone but fails to run with error /usr/bin/env: ‘python3.8’: No such file or directory for newest Kali VM with all updates and run using the Kali-Setup command

**To Reproduce**

1. ... Install newest kali vm
2. ...update it
3. ...pull git clone
4. ...kali-setup
5. Run eaphammer

**Expected behavior**

The program should run

**Screenshots**

**Command string(s) used**

The exact command(s) you used to trigger the bug.
./eaphammer

**EAPHammer verbose output (using the --debug flag)**
└─$ /usr/bin/env: ‘python3.8’: No such file or directory
zsh: no such file or directory: /usr/bin/env:

Paste _redacted_ output here.

**EAPHammer Version (./eaphammer --version)**

Paste output here.

**OS (the OS from which you are running EAPHammer)**
Kali
Fill this in.

**Configuration of Target Access Point (if known / applicable)**

Fill this in if possible.

**Configuration of Target Client Device (if known / applicable)**

Fill this in if possible.

**Additional context**

**Comment by PowerPress** [comment]
Found the fix:

sudo ln -s /usr/bin/python3 /usr/bin/python3.8

git clone https://github.com/s0lst1c3/eaphammer.git

**Comment by whoot** [comment]
Correct fix is discussed in #165

**Comment by varnit-mittal** [comment]
An easy way 
just go inside the folder eaphammer and then write the following command
python3 eaphammer --cert-wizard
and also run all the commands like this only

**Comment by s0lst1c3** [comment]
Resolved 1.14.0
