### ISSUE TITLE
Hostapd wont start bc erro in temp .conf file

### ISSUE THREAD

**Issue by Haze4153** [s0lst1c3/eaphammer#201]
I get a error bc in the temporary hostapd .conf file is a „/„ missing at the start of the path for the ctrl_interface argument.

![7C890786-2DF8-46A5-8884-FE0CA97E2CBB](https://user-images.githubusercontent.com/52799215/229315553-26abc249-4971-4ea2-85f1-b0d2af2dbe0f.png)
![76AC6A00-90E2-4EF3-AD33-2A8AF6E261B9](https://user-images.githubusercontent.com/52799215/229315554-aec8108b-b8c4-4781-bfaa-a3b541e963fe.jpeg)

**Comment by s0lst1c3** [comment]
Resolved 1.14.0
