### ISSUE TITLE
Eaphammer --cert-wizard Error !

### ISSUE THREAD

**Issue by dell-devil** [s0lst1c3/eaphammer#203]
When I'm trying to open or verify the cert-wizard it gave me this error always and I have also changed the eaphammer file python 3.9 to python 3 any solutions to this ?

![eaphammer-error](https://github.com/s0lst1c3/eaphammer/assets/65786119/0906fd65-421b-408a-82e9-7bdc17eaf8d5)

**Comment by s0lst1c3** [comment]
Resolved 1.14.0
