### ISSUE TITLE
libhostapd-eaphammer.so no such file

### ISSUE THREAD

**Issue by Okitask** [s0lst1c3/eaphammer#204]
**Describe the bug**
`OSError: /home/polair/eaphammer/local/hostapd-eaphammer/hostapd/libhostapd-eaphammer.so: cannot open shared object file: No such file or directory`

**To Reproduce**

`./eaphammer -i wlan1 -c 1 --essid FASTWEB-F2D98B --auth wpa-eap --creds`

**Expected behavior**
run that ap

**OS (the OS from which you are running EAPHammer)**

Parrot OS 5.3

**Comment by matthewomccorkle** [comment]
@Okitask run `apt update -y && apt upgrade -y' then run `./kali-setup` from within the cloned eaphammer repository.

**Comment by s0lst1c3** [comment]
Resolved 1.14.0
