### ISSUE TITLE
New Instance of Kali Issue Generating Certs Missing epoll

### ISSUE THREAD

**Issue by 0xSterny** [s0lst1c3/eaphammer#207]
Currently have a new OS install of Kali. The kali install of eaphammer had no issues. However when trying to generate the certificates from the cert-wizard, there seems to be a module error that I cannot diagnose. 

sudo ./eaphammer --cert-wizard

**Screenshots**

![image](https://github.com/s0lst1c3/eaphammer/assets/115005418/979ba13c-1d3d-46f8-bd8b-518092a61861)

**OS (the OS from which you are running EAPHammer)**

Kali Linux 2023.3

**Comment by wretiii** [comment]
You can bypass this issue by running EAPHammer in a Python3 virtual environment.

**Comment by rouxn-bsi** [comment]
sudo **EVENTLET_NO_GREENDNS="yes"** ./eaphammer --cert-wizard
