### ISSUE TITLE
[*] Saving current iptables configuration...

### ISSUE THREAD

**Issue by tjt263** [s0lst1c3/eaphammer#36]
Probably innocuous, but all flags seem to trigger the condition to save the current `iptables` config, or at least print the `[*] Saving current iptables configuration...`.  It even prepends the usage screen triggered by the `-h`/`--help` flags.

Doesn't really bother me, but I thought I ought to say something. I haven't had time to check it out.

**Comment by s0lst1c3** [comment]
Yeah, the functionality for this needs to be moved out of main() in project_root/eaphammer to the individual driver functions used to launch each attack. Thanks for pointing that out.

**Comment by s0lst1c3** [comment]
Closed the issue, thanks again @tjt263 for pointing this out.
