### ISSUE TITLE
Where does negotiation happen?

### ISSUE THREAD

**Issue by redfast00** [s0lst1c3/eaphammer#49]
According to the docs:

> There is no need to specify an EAP type, as eaphammer will negotiate the EAP type on a victim-by-victim basis as they connect to the rogue AP. EAPHammer will automatically use the least secure EAP type supported by the client in order to make cracking attempts easier.

In what source file does this happen? What EAP types will be tried?

Thanks!

**Comment by s0lst1c3** [comment]
Oops! I am so sorry, I fatfingered the "Close" button and closed your issue. Reasons not to use Git at 3am! 🤣 

To answer your question: this functionality actually carries over from hostapd-wpe, from which the hostapd component of eaphammer is forked from. I'm not exactly sure where it's implemented, although I'll grep around for it and get back to you.

As far as what EAP types that are tried, hostapd-wpe supports each of the following types:
hostapd-wpe supports the following EAP types:

1. EAP-FAST/MSCHAPv2 (Phase 0)
2. PEAP/MSCHAPv2
3. EAP-TTLS/MSCHAPv2
4. EAP-TTLS/MSCHAP
5. EAP-TTLS/CHAP
6. EAP-TTLS/PAP

I'm actually in the process of pushing my changes to hostapd into https://github.com/sensepost/hostapd-mana, then migrating to a fork of that project instead. Hostapd-mana supports a much longer list of EAP types, which should make the tool much more effective (see: https://github.com/sensepost/hostapd-mana/wiki/MANA-EAP-Options-(aka-WPE)).

Hope that helps!

**Comment by s0lst1c3** [comment]
Closing since this looks like a dead issue at this point.
