### ISSUE TITLE
eap-spray not iterating?

### ISSUE THREAD

**Issue by burnnotice** [s0lst1c3/eaphammer#59]
Hello,

I was trying to use the password spray technique recently and I couldn't get it to move on past the first combination of test credentials. I have tried with an Alfa awus036h and an alfa awus036ach wireless card on the latest Kali 64-bit VM build. Below is sample output:

root@kali:/opt/eaphammer# ./eaphammer --eap-spray --interface-pool wlan0 --essid <WIFINAME> --password testing --user-list users.txt

                     .__                                         
  ____ _____  ______ |  |__ _____    _____   _____   ___________ 
_/ __ \\__  \ \____ \|  |  \\__  \  /     \ /     \_/ __ \_  __ \
\  ___/ / __ \|  |_> >   Y  \/ __ \|  Y Y  \  Y Y  \  ___/|  | \/
 \___  >____  /   __/|___|  (____  /__|_|  /__|_|  /\___  >__|   
     \/     \/|__|        \/     \/      \/      \/     \/       

                            "Unrelenting Force"

                                v0.5.0
    
[wlan0] Trying credentials: test:testing@<WIFINAME>
Successfully initialized wpa_supplicant
[wlan0] CTRL-EVENT-SCAN-FAILED ret=-16 retry=1
[wlan0] CTRL-EVENT-SCAN-FAILED ret=-16 retry=1
[wlan0] CTRL-EVENT-SCAN-FAILED ret=-16 retry=1
[wlan0] SME: Trying to authenticate with 20:37:06:a5:b4:40 (SSID='<WIFINAME>' freq=2412 MHz)
[wlan0] Trying to associate with 20:37:06:a5:b4:40 (SSID='<WIFINAME>' freq=2412 MHz)
[wlan0] Associated with 20:37:06:a5:b4:40
[wlan0] CTRL-EVENT-SUBNET-STATUS-UPDATE status=0
[wlan0] CTRL-EVENT-DISCONNECTED bssid=20:37:06:a5:b4:40 reason=3 locally_generated=1
[wlan0] CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
[wlan0] SME: Trying to authenticate with 20:37:06:aa:67:00 (SSID='<WIFINAME>' freq=2462 MHz)
[wlan0] Trying to associate with 20:37:06:aa:67:00 (SSID='<WIFINAME>' freq=2462 MHz)
[wlan0] Associated with 20:37:06:aa:67:00
[wlan0] CTRL-EVENT-SUBNET-STATUS-UPDATE status=0
[wlan0] CTRL-EVENT-DISCONNECTED bssid=20:37:06:aa:67:00 reason=3 locally_generated=1
[wlan0] CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
[wlan0] SME: Trying to authenticate with 20:37:06:a5:da:70 (SSID='<WIFINAME>' freq=2437 MHz)
[wlan0] Trying to associate with 20:37:06:a5:da:70 (SSID='<WIFINAME>' freq=2437 MHz)
[wlan0] SME: Trying to authenticate with 20:37:06:a5:e9:10 (SSID='<WIFINAME>' freq=2437 MHz)
[wlan0] Trying to associate with 20:37:06:a5:e9:10 (SSID='<WIFINAME>' freq=2437 MHz)
[wlan0] Associated with 20:37:06:a5:e9:10
[wlan0] CTRL-EVENT-SUBNET-STATUS-UPDATE status=0
[wlan0] CTRL-EVENT-DISCONNECTED bssid=20:37:06:a5:e9:10 reason=3 locally_generated=1
[wlan0] CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
[wlan0] SME: Trying to authenticate with 20:37:06:7c:83:f0 (SSID='<WIFINAME>' freq=2437 MHz)
[wlan0] Trying to associate with 20:37:06:7c:83:f0 (SSID='<WIFINAME>' freq=2437 MHz)
[wlan0] SME: Trying to authenticate with 40:f4:ec:a3:ba:d0 (SSID='<WIFINAME>' freq=2412 MHz)
[wlan0] Trying to associate with 40:f4:ec:a3:ba:d0 (SSID='<WIFINAME>' freq=2412 MHz)
[wlan0] SME: Trying to authenticate with 20:37:06:a5:ce:50 (SSID='<WIFINAME>' freq=2462 MHz)
[wlan0] Trying to associate with 20:37:06:a5:ce:50 (SSID='<WIFINAME>' freq=2462 MHz)
[wlan0] CTRL-EVENT-ASSOC-REJECT bssid=20:37:06:a5:ce:50 status_code=17
[wlan0] SME: Deauth request to the driver failed
[wlan0] SME: Trying to authenticate with 40:f4:ec:61:e8:c0 (SSID='<WIFINAME>' freq=2437 MHz)
[wlan0] Trying to associate with 40:f4:ec:61:e8:c0 (SSID='<WIFINAME>' freq=2437 MHz)
[wlan0] SME: Trying to authenticate with 20:37:06:a5:b4:40 (SSID='<WIFINAME>' freq=2412 MHz)
[wlan0] Trying to associate with 20:37:06:a5:b4:40 (SSID='<WIFINAME>' freq=2412 MHz)
[wlan0] Associated with 20:37:06:a5:b4:40
[wlan0] CTRL-EVENT-SUBNET-STATUS-UPDATE status=0
[wlan0] CTRL-EVENT-DISCONNECTED bssid=20:37:06:a5:b4:40 reason=3 locally_generated=1
[wlan0] CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
[wlan0] SME: Trying to authenticate with 20:37:06:aa:67:00 (SSID='<WIFINAME>' freq=2462 MHz)
[wlan0] Trying to associate with 20:37:06:aa:67:00 (SSID='<WIFINAME>' freq=2462 MHz)
[wlan0] SME: Trying to authenticate with 20:37:06:a5:da:70 (SSID='<WIFINAME>' freq=2437 MHz)
[wlan0] Trying to associate with 20:37:06:a5:da:70 (SSID='<WIFINAME>' freq=2437 MHz)
[wlan0] Associated with 20:37:06:a5:da:70
[wlan0] CTRL-EVENT-SUBNET-STATUS-UPDATE status=0
[wlan0] CTRL-EVENT-DISCONNECTED bssid=20:37:06:a5:da:70 reason=3 locally_generated=1
[wlan0] CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
[wlan0] SME: Trying to authenticate with 20:37:06:a5:ce:50 (SSID='<WIFINAME>' freq=2462 MHz)
[wlan0] Trying to associate with 20:37:06:a5:ce:50 (SSID='<WIFINAME>' freq=2462 MHz)
[wlan0] CTRL-EVENT-ASSOC-REJECT bssid=20:37:06:a5:ce:50 status_code=17
[wlan0] SME: Deauth request to the driver failed
[wlan0] SME: Trying to authenticate with 20:37:06:a5:e9:10 (SSID='<WIFINAME>' freq=2437 MHz)
[wlan0] Trying to associate with 20:37:06:a5:e9:10 (SSID='<WIFINAME>' freq=2437 MHz)
[wlan0] Associated with 20:37:06:a5:e9:10
[wlan0] CTRL-EVENT-SUBNET-STATUS-UPDATE status=0
[wlan0] CTRL-EVENT-DISCONNECTED bssid=20:37:06:a5:e9:10 reason=3 locally_generated=1
[wlan0] CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
[wlan0] CTRL-EVENT-REGDOM-CHANGE init=COUNTRY_IE type=COUNTRY alpha2=US
[wlan0] SME: Trying to authenticate with 20:37:06:a5:b4:40 (SSID='<WIFINAME>' freq=2412 MHz)
[wlan0] Trying to associate with 20:37:06:a5:b4:40 (SSID='<WIFINAME>' freq=2412 MHz)
[wlan0] CTRL-EVENT-ASSOC-REJECT bssid=20:37:06:a5:b4:40 status_code=17
[wlan0] SME: Deauth request to the driver failed
[wlan0] CTRL-EVENT-SSID-TEMP-DISABLED id=0 ssid="<WIFINAME>" auth_failures=1 duration=10 reason=CONN_FAILED
[wlan0] CTRL-EVENT-SSID-REENABLED id=0 ssid="<WIFINAME>"
[wlan0] SME: Trying to authenticate with 20:37:06:aa:5c:50 (SSID='<WIFINAME>' freq=2412 MHz)
[wlan0] Trying to associate with 20:37:06:aa:5c:50 (SSID='<WIFINAME>' freq=2412 MHz)
[wlan0] CTRL-EVENT-ASSOC-REJECT bssid=20:37:06:aa:5c:50 status_code=17
[wlan0] SME: Deauth request to the driver failed
[wlan0] CTRL-EVENT-SSID-TEMP-DISABLED id=0 ssid="<WIFINAME>" auth_failures=2 duration=23 reason=CONN_FAILED
[wlan0] CTRL-EVENT-SSID-REENABLED id=0 ssid="<WIFINAME>"
[wlan0] SME: Trying to authenticate with 20:37:06:aa:67:00 (SSID='<WIFINAME>' freq=2462 MHz)
[wlan0] Trying to associate with 20:37:06:aa:67:00 (SSID='<WIFINAME>' freq=2462 MHz)
[wlan0] Associated with 20:37:06:aa:67:00
[wlan0] CTRL-EVENT-SUBNET-STATUS-UPDATE status=0
[wlan0] CTRL-EVENT-DISCONNECTED bssid=20:37:06:aa:67:00 reason=3 locally_generated=1
[wlan0] CTRL-EVENT-SSID-TEMP-DISABLED id=0 ssid="<WIFINAME>" auth_failures=3 duration=46 reason=CONN_FAILED
[wlan0] CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
[wlan0] CTRL-EVENT-SSID-REENABLED id=0 ssid="<WIFINAME>"
[wlan0] SME: Trying to authenticate with 20:37:06:a5:b4:40 (SSID='<WIFINAME>' freq=2412 MHz)
[wlan0] Trying to associate with 20:37:06:a5:b4:40 (SSID='<WIFINAME>' freq=2412 MHz)
[wlan0] Associated with 20:37:06:a5:b4:40
[wlan0] CTRL-EVENT-SUBNET-STATUS-UPDATE status=0
[wlan0] CTRL-EVENT-DISCONNECTED bssid=20:37:06:a5:b4:40 reason=3 locally_generated=1
[wlan0] CTRL-EVENT-SSID-TEMP-DISABLED id=0 ssid="<WIFINAME>" auth_failures=4 duration=77 reason=CONN_FAILED
[wlan0] CTRL-EVENT-REGDOM-CHANGE init=CORE type=WORLD
^C^CTerminated

Am I derping something up here? Thank you for your help.

**Comment by s0lst1c3** [comment]
Resolved by #157
