### ISSUE TITLE
Feature Request: GTC Downgrade Attacks (orig: Plaintext passwords !)

### ISSUE THREAD

**Issue by minanagehsalalma** [s0lst1c3/eaphammer#63]
Is this possible ?

**Comment by illera88** [comment]
It can. Need to do the GTC downgrade attack.

**Comment by minanagehsalalma** [comment]
@illera88 
> which is used by this project does not support it
so it can't !?

**Comment by s0lst1c3** [comment]
@minanagehsalalma GTC downgrade attacks are in the pipeline.

**Comment by W00t3k** [comment]
It can. @minanagehsalalma - the README needs to be updated.

https://twitter.com/W00Tock/status/1019251419310972930

**Comment by minanagehsalalma** [comment]
@W00t3k  great   ... which commend should I use to active  it ?

**Comment by minanagehsalalma** [comment]
@s0lst1c3  so what is the full command to run it ?
