### ISSUE TITLE
Kali 2019.1 error: ModuleNotFoundError: No module named 'tqdm'

### ISSUE THREAD

**Issue by clive7391** [s0lst1c3/eaphammer#65]
Fresh Kali 2019.1 installed Version 0.5.1 via git and then ./kali-setup
Upon running, receive error-
  File "./eaphammer", line 4, in <module>
    import core.cli
  File "/root/eaphammer/core/__init__.py", line 2, in <module>
    from . import conf_manager
  File "/root/eaphammer/core/conf_manager.py", line 3, in <module>
    import core.utils
  File "/root/eaphammer/core/utils.py", line 5, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'

sudo apt install python-tqdm

python-tqdm is already the newest version (4.28.1-1).
python-tqdm set to manually installed.

Error on X64 and Arm

Error not on 0.4.0

**Comment by MBLAHO13** [comment]
`python3 -m pip install tqdm`

The shebang in the file is /usr/bin/env python3. Your pip environment defaults to 2.7, and the module is installed in 2.7's environment. You need to install it in python 3's environment. 

This is a common problem with python scripts under Kali, and this is the general case of fixing them. Invoke the pip module with python3, and pass the command to it. Hope this fixes your problem.

**Comment by clive7391** [comment]
Thank you for your assistance. This did fix the issue!
Closed...

**Comment by freqyXin** [comment]
This error is back in the newest version, except pem is missing as well.

ModuleNotFoundError: No module named 'pem'

Use @MBLAHO13 's fix with pem as required.

`python3 -m pip install pem`

**Comment by hackvice** [comment]
Same here unable to fix the issue even after python3 -m pip install pem
