### ISSUE TITLE
TLS: Failed to set DH params from '/root/eaphammer/certs/dh': error:1408518A:SSL routines:ssl3_ctx_ctrl:dh key too small

### ISSUE THREAD

**Issue by freqyXin** [s0lst1c3/eaphammer#69]
Had some issues running:
`--creds`

&

 `--hostile-portal -auth wpa`

These resulted in an error and failure to enable AP.

Error:
TLS: Failed to set DH params from '/root/eaphammer/certs/dh': error:1408518A:SSL routines:ssl3_ctx_ctrl:dh key too small

This is due to the length of the dh key eaphammer is packaged with --it's 1024 bit.

To fix this issue (Kali):
1. `cd eaphammer/certs/`
2. `rm dh`
3.  Generate a new 2048 bit dh key:
           `sudo openssl dhparam -out dh 2048`

**Comment by ZeroChaos-** [comment]
@freqyXin The offending line is here https://github.com/s0lst1c3/eaphammer/blob/master/certs/Makefile#L12

I bet you can make a PR with a fix :-)

**Comment by freqyXin** [comment]
Just made the PR, ty for finding that @ZeroChaos-

**Comment by s0lst1c3** [comment]
You guys are awesome for sorting this out. Coincidentally, I’m literally about to push an update that completely revamps EAPHammer’s certificate generation and handling, and should solve this issue. I just need to finish the related documentation, which I’m working on as we speak. In the meantime, you could switch to the project’s “cert_handling” branch, which addresses this issue by using a default DH length of 2048z

**Comment by s0lst1c3** [comment]
@freqyXin Also, I’ll make sure to merge your pull request prior to merging the cert_handling branch so that you get credit for contributing. ;)
