### ISSUE TITLE
PMKID Attack does not work

### ISSUE THREAD

**Issue by zwt2135** [s0lst1c3/eaphammer#75]
I love eaphammer its a fantastic tool. However I can not seem to get pmkid attack to work. I have a fully update kali linux as well as a directly download version of eaphammer. I get the following response.

Any ideas would be appreciated!

[*] Bringing wlan0 down...
[*] Complete!
[*] Reticulating radio frequency splines...

[*] Using nmcli to tell NetworkManager not to manage wlan0...

100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.00s/it]

[*] Success: wlan0 no longer controlled by NetworkManager.
[*] Placing wlan0 into managed mode...
[*] Complete!
[*] Bringing wlan0 up...
[*] Complete!
[*] Scanning for nearby access points...
Traceback (most recent call last):
  File "./eaphammer", line 608, in <module>
    pmkid_attack()
  File "./eaphammer", line 336, in pmkid_attack
    networks = iw_parse.iw_parse.get_interfaces(interface=str(interface))
  File "/root/eaphammer/core/iw_parse/iw_parse.py", line 284, in get_interfaces
    return get_parsed_cells(call_iwlist(interface).split('\n'))
TypeError: a bytes-like object is required, not 'str'

**Comment by s0lst1c3** [comment]
Thanks for catching this. At first glance, I think this is a type issue
introduced when EAPHammer was ported to Python 3 (see:
https://twitter.com/s0lst1c3/status/1093740080366182401). I should be able
to get this fixed fairly quickly, just need to carve out the time for it
over the next couple days. Really appreciate the bug report.

**Comment by zwt2135** [comment]
Hey no problem glad to help! Like I said I love Eap hammer it's a fantastic tool. I have used it a ton since i found out about it. 

Any word on if the issue has been fixed yet?

**Comment by s0lst1c3** [comment]
Not quite yet. It looks like the entire iw_parse module needs to be fixed to work with Python 3's string characteristics. 

https://github.com/s0lst1c3/eaphammer/tree/master/core/iw_parse

Fortunately, it's not a very large module.

**Comment by zwt2135** [comment]
At least we know what the issue is! I look forward to being able to use the pmkid function. Great work again!

**Comment by shinhub** [comment]
Issue also found here #99

**Comment by shinhub** [comment]
It appears that it is really simply fixed. Need checking.
In core/iw_parse/iw_parse.py, because <FILE>.read() returns a "bytes" chain in Python3, the return value has to be decoded as a string ([see this for a crash course on Python3 strings and bytes](https://medium.com/better-programming/strings-unicode-and-bytes-in-python-3-everything-you-always-wanted-to-know-27dc02ff2686)). Supposed UTF-8 would be the safest, as we cannot assume system default encoding, Python3 is supposed to be UTF-8 default, and worked fine for me.
```
def call_iwlist(interface='wlan0'):
    [...]
    return p.stdout.read().decode("utf-8")
```

**Comment by s0lst1c3** [comment]
Fix for this is still in the pipeline (soon!). In the meantime, support for WPA/2-PSK and WPA handshake captures have been added to `--creds` mode, which should accomplish the same goal (with more reliability) so long as clients are present.

**Comment by pk-r7** [comment]
Similar results with the command:
./eaphammer --eap-spray -I wlan0 --essid "target" --user-list /root/empbrute --password "weaksauce"


[wlan0] Trying credentials: "redacted"
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/eaphammer/core/eap_spray/worker.py", line 34, in _start
    if wpa_supplicant.test_creds():
  File "/opt/eaphammer/core/wpa_supplicant.py", line 18, in test_creds
    print(line.replace('%s:' % self.interface, '[%s]' % self.interface), end=' ')
TypeError: a bytes-like object is required, not 'str'

**Comment by kur3us** [comment]
Any update on the fix for this? Thanks!

**Comment by bryce-lynch** [comment]
Same issue here.

I've tried shinhub's suggestion, and although the TypeErrors disappear, it still doesn't work (I only get an endless list of spaces printed on screen)

**Comment by elobato92** [comment]
I ran into this error during an engagement today, is there any plan to fix this issue? Thanks!
