### ISSUE TITLE
No Deauth feature?

### ISSUE THREAD

**Issue by suwmr** [s0lst1c3/eaphammer#9]
Hi s0lst1ce i'm testing your tool and i've found it very interesting! as said before, running eaphammer kills other process who include the NIC so i can't figure out how to perform deauth attack to let the victim connect to my evil twin. 
keep it on i'm very curious about future features!!!
i wonder... what about this: while i set the evil twin whit the wpa authentication, eaphammer should try to auto authenticate to the real ssid? maybe reading from a .py tcp client/server for the network rules... 
great job!!

**Comment by s0lst1c3** [comment]
> Hi s0lst1ce i'm testing your tool and i've found it very interesting!

Thanks! xD

>  running eaphammer kills other process who include the NIC so i can't figure out how to perform deauth attack to let the victim connect to my evil twin.

As of 78fa673be9dcf132b3c5e37dbcb04fceb8135e63, EAPHammer will no longer completely disable NetworkManager. Instead, it will use nmcli to instruct NetworkManager to temporarily ignore the interface that you provide using the --interface flag. Here's the catch though: EAPHammer still needs that interface to create the access point. It's not possible to use a wireless interface to simultaneously create an AP and perform a deauth attack. This means that you're going to need to use a second wireless interface to perform the deauth. At some point, a dedicated deauth engine will be included with EAPHammer, but for now you can still get really good results using aireplay-ng. 

Going to close this issue for now.
