### ISSUE TITLE
undefined symbol: wpa_auth_write_assoc_resp_owe

### ISSUE THREAD

**Issue by edoz90** [s0lst1c3/eaphammer#93]
Hi!

I'm using Archlinux and I've followed and installed all the packages required by eaphammer but when I run the command

`eaphammer -i wlan1 --auth wpa --wpa-version 2 --essid fakewifi --bssid xx:xx:xx:xx:xx:xx --creds`

I get this output:

```
[?] Am I root?
[*] Checking for rootness...
[*] I AM ROOOOOOOOOOOOT
[*] Root privs confirmed! 8D
[*] Saving current iptables configuration...
[*] Reticulating radio frequency splines...

[*] Using nmcli to tell NetworkManager not to manage wlan1...

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.00s/it]

[*] Success: wlan1 no longer controlled by NetworkManager.
Traceback (most recent call last):
  File "./eaphammer", line 634, in <module>
    reap_creds()
  File "./eaphammer", line 294, in reap_creds
    hostapd.start()
  File "/root/eaphammer/core/hostapd.py", line 40, in start
    self.libhostapd = ctypes.cdll.LoadLibrary(self.lib_path)
  File "/usr/lib64/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib64/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /root/eaphammer/local/hostapd-eaphammer/hostapd/libhostapd-eaphammer.so: undefined symbol: wpa_auth_write_assoc_resp_owe
```

**Comment by s0lst1c3** [comment]
Did you figure it out?

**Comment by edoz90** [comment]
Yeah! Sorry for the trouble....

I simply reinstalled all the deps using `./kali-setup` ignoring Kali updates and pkgs installation.

**Comment by edoz90** [comment]
Sorry but I need to reopen this issue since another clean install on Archlinux produces the same error.
The installation/compilation phase of eaphammer works well only on kali.

**Comment by s0lst1c3** [comment]
Did you copy `local/hostapd-eaphammer/hostapd/defconfig` to `local/hostapd-eaphammer/hostapd/.config` before running `make`?

**Comment by okiwoki** [comment]
I'm also getting a similar error on Kali for Raspberry Pi when just running `./eaphammer -i wlan0`:

`OSError: /opt/eaphammer/local/hostapd-eaphammer/hostapd/libhostapd-eaphammer.so: undefined symbol: wpa_ft_parse_ies`

Tried copying `defconfig` as `.config` to `local/hostapd-eaphammer/hostapd` and still got the same error

**Comment by s0lst1c3** [comment]
@edoz90  Arch Linux isn't officially supported but it's on my todo list. 

@okiwoki Did you run into this error when trying to upgrading your existing repository? Or on a completely fresh install? Do you mind posting the exact version of Kali you're using? There might be some nuances that apply specifically to running Kali on a Pi that I haven't taken into account.

**Comment by okiwoki** [comment]
> @okiwoki Did you run into this error when trying to upgrading your existing repository? Or on a completely fresh install? Do you mind posting the exact version of Kali you're using? There might be some nuances that apply specifically to running Kali on a Pi that I haven't taken into account.

@s0lst1c3 I was actually having the same issue on Linux Mint as well and did the same thing to fix it (completely removed eaphammer, git cloned, then ran kali-setup). What led to the error before was when I git pulled the updated files and tried to run kali-setup again. I never got a compilation error so I assumed all was fine. Complete removal and running kali-setup again fixed it for both Linux Mint and Kali on the Pi though.

**Comment by s0lst1c3** [comment]
@okiwoki 
@edoz90 

It sounds like the core issues are:
- EAPHammer lacks a reliable update script
- EAPHammer lacks setup scripts for distros aside from Kali

Given the widespread demand for these features, I've opened official feature requests to address this. For your issues in particular, see #114, #110, and #113. Closing this issue to avoid redundancy.
