### ISSUE TITLE
Parrot OS- "Hostapd-Eaphammer: Invalid Option --'N' 

### ISSUE THREAD

**Issue by kozlovsas** [s0lst1c3/eaphammer#94]
I'm getting the following error after setting up and installing related packages and modules, generating a cert for EAPHammer, then running the command:
eaphammer/local/hostapd-eaphammer/hostapd/hostapd-eaphammer: invalid option -- 'N'

I haven't found a way to disable or debug this option anywhere in eaphammer just yet, the only clue I recieve is my hostapd version:
hostapd v2.9-devel
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2019, Jouni Malinen <j@w1.fi> and contributors
[hostapd] AP starting...

I'm not sure if it's supposed to be that new, the hostapd-eaphammer package is version 2.6

Has anyone else encountered this issue on Parrot or another Linux distro?

**Comment by s0lst1c3** [comment]
Hi @kozlovsas,

Can you please try the following commands from your project root directory?

**Command(s):**

```bash
cd local/hostapd-eaphammer/hostapd
make clean
cp defconfig .config 
make hostapd-eaphammer_lib 
```

**Comment by kozlovsas** [comment]
Yep this worked, thanks very much @s0lst1c3 !

As a follow-up, I'm now getting "TLS: Failed to open DH eaphammer/certs/dh': error:02001002:system library:fopen:No such file or directory"

I checked that directory, and I don't have a "dh" folder or file in there.

**Comment by s0lst1c3** [comment]
Looks like you need to generate some Diffie-Hellman (DH) parameters!  ;) The DH parameters are generated automagically when you run `./kali-setup`, but since you're building the project by hand it's likely this didn't happen.

First, go read @singe's primer on configuring EAP access points. It's a quick read and will give you a bit more context as to what the underlying issue is.

[https://github.com/sensepost/hostapd-mana/wiki/Creating-PSK-or-EAP-Networks](https://github.com/sensepost/hostapd-mana/wiki/Creating-PSK-or-EAP-Networks)

Then, run `eaphammer` with the `--cert-wizard dh` flag to generate a DH file as shown in the following example:

Command(s):

```bash
./eaphammer --cert-wizard dh
```

Result:

```bash
root@kali:~/eaphammer# ./eaphammer --cert-wizard dh

                     .__                                         
  ____ _____  ______ |  |__ _____    _____   _____   ___________ 
_/ __ \\__  \ \____ \|  |  \\__  \  /     \ /     \_/ __ \_  __ \
\  ___/ / __ \|  |_> >   Y  \/ __ \|  Y Y  \  Y Y  \  ___/|  | \/
 \___  >____  /   __/|___|  (____  /__|_|  /__|_|  /\___  >__|   
     \/     \/|__|        \/     \/      \/      \/     \/       

                            "Unrelenting Force"

                                v1.3.0
    
[?] Am I root?
[*] Checking for rootness...
[*] I AM ROOOOOOOOOOOOT
[*] Root privs confirmed! 8D

[*] Rebuilding DH parameters file with length of 2048...

Generating DH parameters, 2048 bit long safe prime, generator 2
This is going to take a long time
..................................................................................................................................................................................................................................................................................................................................................
...snip...
................................+.......+.....................+.........................................................
root@kali:~/eaphammer#
```

You should be good to go after that.

**Comment by kozlovsas** [comment]
Awesome thank you @s0lst1c3 , I ended up getting another error with openssl after that. For some reason, the way the kali-setup script compiles hostapd-eaphammer_lib was messed up on my system, so I removed the compilation process through the script and completed it manually after.

After I commented out the os.system commands to compile hostapd and re-ran the kali setup script I was able to run eaphammer! 

If I may, I gotta bug you about one last issue. I may be doing the attack wrong, but I'm trying to capture creds from a dev EAP PEAP network. When I run eaphammer (or hostapd_wpe by itself) with the capture creds attack, I get the following output:
wlan1: STA 78:88:6d:5c:a7:75 IEEE 802.11: associated
wlan1: CTRL-EVENT-EAP-STARTED 78:88:6d:5c:a7:75
wlan1: CTRL-EVENT-EAP-PROPOSED-METHOD vendor=0 method=1
wlan1: CTRL-EVENT-EAP-PROPOSED-METHOD vendor=0 method=25
wlan1: STA 78:88:6d:5c:a7:75 IEEE 802.11: disassociated
wlan1: STA 78:88:6d:5c:a7:75 IEEE 802.11: associated
wlan1: CTRL-EVENT-EAP-STARTED 78:88:6d:5c:a7:75
wlan1: CTRL-EVENT-EAP-PROPOSED-METHOD vendor=0 method=1
wlan1: CTRL-EVENT-EAP-PROPOSED-METHOD vendor=0 method=25
wlan1: STA 78:88:6d:5c:a7:75 IEEE 802.11: disassociated
wlan1: STA 78:88:6d:5c:a7:75 IEEE 802.11: associated
wlan1: CTRL-EVENT-EAP-STARTED 78:88:6d:5c:a7:75
wlan1: CTRL-EVENT-EAP-PROPOSED-METHOD vendor=0 method=1
wlan1: CTRL-EVENT-EAP-PROPOSED-METHOD vendor=0 method=25
wlan1: STA 78:88:6d:5c:a7:75 IEEE 802.11: disassociated

Would you happen to have any idea as to what I'm missing/doing wrong? Here's my command:
sudo ./eaphammer --creds -i wlan1 --auth wpa -c 2 --essid "Test"

Thank you again for all your assistance and hard work.

**Comment by s0lst1c3** [comment]
No problem!

My best guess is that the client is wandering back and forth between your rogue AP and the target AP due to similar signal quality. For liability reasons, that's about all the practical advice I can give in terms of actually using the tool.

Closing since this is no longer a support thread.

Cheers!
